@hostname = localhost
@port = 3001
@host = http://{{hostname}}:{{port}}

### READ ALL RAW QUERY
GET {{host}}/more
Accept: application/json

### CREATE ONE  TRANSACTION
POST {{host}}/more
Accept: application/json
Content-Type: application/json

{
  "CompanyName": "Transactionbdc"
}