@hostname = localhost
@port = 3001
@host = http://{{hostname}}:{{port}}


### CREATE ONE
POST {{host}}/orders
Accept: application/json
Content-Type: application/json

{
  "ShipName": "Order ship",
  "ShipCity": "ABC"
}


### READ ALL
GET {{host}}/orders
Accept: application/json

### READ WHERE
GET {{host}}/orders/cndtn?ShipCity=ABC
Accept: application/json

### READ ONE
GET {{host}}/orders/1
Accept: application/json

### DELETE ALL
DELETE {{host}}/orders/
Accept: application/json

### DELETE ONE
DELETE {{host}}/orders/5
Accept: application/json